Feat: Average Blending
brown-ccv/react-volume-viewer pull request #116
Opened 2022-06-03 19:05 UTC by RobertGemmaJr

Adds logic for blending the average of each model.

The GLSL `mix()` function mixes based on a percentage (0 - 1) of the two inputs. The ratio of the first input (`v_sample.a`) to the total (`v_sample.a + m_sample.a`) yields that percentage. 

- closes #112 
- closes #115

2022-06-07 18:10 UTC, broarr approved these changes

2022-06-10 19:42 UTC, kmilo9999 reviewed
👍  keep the good work !

2022-06-10 19:42 UTC, kmilo9999 commented on src/aframe/fragment-shader.frag
place  `model_sample.rgb *= model.intensity;`  here. So the value of the pixel only gets increased once per model and not once per sample.

2022-06-10 19:42 UTC, kmilo9999 commented on src/aframe/fragment-shader.frag
> +    vec4 m_sample, v_sample;
`m_sample ` is only used inside the internal for loop. you can move it below `if(blending != 0)`

2022-06-10 19:43 UTC, kmilo9999 requested changes
Adding comments to my review

2022-06-10 20:10 UTC, RobertGemmaJr commented on example/src/App.js
> -      blending={Blending.Max}
Will do!

2022-06-10 20:11 UTC, RobertGemmaJr commented on src/aframe/fragment-shader.frag
Actually yeah I refactored a little more to calculate the mix factor correctly and it doesn't actually make a difference? Should each model have its own intensity or should it be a property of the volume itself that's calculated after all of the blending is done?

2022-06-10 20:13 UTC, RobertGemmaJr commented on src/aframe/fragment-shader.frag
> +    vec4 m_sample, v_sample;
Moved it

2022-06-10 20:15 UTC, kmilo9999 commented on src/aframe/fragment-shader.frag
it should be calculated after all the blending is done. let's apply the max intensity of the models.

2022-06-10 20:24 UTC, RobertGemmaJr commented on src/aframe/fragment-shader.frag
Okay it should be all set!

2022-06-16 18:50 UTC, RobertGemmaJr commented
@eldu can you take a look at the shader code while Camilo is on vacation? Thank you!

2022-06-16 19:27 UTC, RobertGemmaJr commented
Consolidating with other Blending changes to #131

2022-06-16 19:27 UTC, closed without merging

2022-06-17 12:33 UTC, eldu reviewed
Added in some comments and questions! Looks good to me though !