fix blend intensity
brown-ccv/react-volume-viewer pull request #136
Opened 2022-07-22 16:20 UTC by kmilo9999

remove intensity calculation based on maximum value per group of voxels. changed to individual value per voxel

2022-07-22 19:31 UTC, RobertGemmaJr requested changes
Looks great! I would lint the tabbing to be safe.

Make sure you do a version bump in `package.json`, otherwise the new release won't work.

2022-07-25 18:27 UTC, RobertGemmaJr reviewed
Looks great! Something messed up with the dependencies on your local repo though. I added the suggested changes to fix them and then it's good to go!

2022-07-25 18:27 UTC, RobertGemmaJr commented on package.json
> +    "bootstrap": "^4.6",
Only the version bump should have changed, not sure what's going on with all the dependencies
```suggestion
```

2022-07-25 18:27 UTC, RobertGemmaJr commented on package.json
> +    "web-vitals": "^1.0.1"
```suggestion
```

2022-07-25 18:27 UTC, RobertGemmaJr commented on package.json
> +    "prettier-plugin-glsl": "^0.0.4",
Can you change this to a dev dependency?

```console
npm uninstall prettier-plugin-glsl
```

```console
npm install prettier-plugin-glsl --save-dev

2022-07-25 18:27 UTC, RobertGemmaJr commented on src/aframe/fragment-shader.frag
>  }
Just adding a newline to the end of the file
```suggestion
}

```

2022-07-25 18:56 UTC, kmilo9999 commented on package.json
> +    "bootstrap": "^4.6",
I removed it

2022-07-25 18:56 UTC, kmilo9999 commented on package.json
> +    "web-vitals": "^1.0.1"
I removed them

2022-07-25 18:57 UTC, kmilo9999 commented on src/aframe/fragment-shader.frag
>  }
I added the new line at the end of the file. The spaces between the equals sign were already there.

2022-07-25 19:25 UTC, RobertGemmaJr approved these changes
Perfect! I'll merge and create the new release

2022-07-25 19:25 UTC, merged