Npm deployment
brown-ccv/react-volume-viewer pull request #24
Opened 2021-11-22 17:10 UTC by RobertGemmaJr

Okay lets try this again. Left the version number as 0.1.0 and included the updated README. I'll work on the changes to opacity controls in the correct branch.

- closes issue #13 
- closes issue #15

2021-11-22 18:59 UTC, mcmcgrath13 requested changes
This looks closer! Add the automation so that it goes to npm on release and I think you're good to go.

2021-11-22 19:37 UTC, RobertGemmaJr commented
Added the recommended npm-publish action but I'm not sure it's setup correctly. I don't think there is a `npm ci` script for this package? Also not sure about the tokens, I created one with the NPM account as `NPM_AUTH_TOKEN` but I don't know where it's supposed to go

2021-11-22 22:09 UTC, mcmcgrath13 commented
> Added the recommended npm-publish action but I'm not sure it's setup correctly. I don't think there is a `npm ci` script for this package? Also not sure about the tokens, I created one with the NPM account as `NPM_AUTH_TOKEN` but I don't know where it's supposed to go

`npm ci` is the same as `npm install` but strictly adheres to the `package-lock.json`.  The token should be added to the repo's secrets (in settings) and then you can reference it in the action as `${ { secrets.NPM_AUTH_TOKEN }}`

2021-11-22 22:14 UTC, mcmcgrath13 requested changes

2021-11-22 22:14 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
> +    types: [created]
```suggestion
    types: [released]
```

2021-11-22 22:14 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
> +      - run: npm test
do we have tests to run? (ideally we should, but we might not yet)

2021-11-22 22:14 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
> +  publish-gpr:
let's skip this job, gpr is annoying to deal with

2021-11-22 22:14 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```suggestion
```

2021-11-22 22:14 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
> +      - run: npm test
this also seems redundant with the next job, so let's delete it

2021-11-22 23:23 UTC, RobertGemmaJr commented on .github/workflows/npm-publish.yml
> +      - run: npm test
There is an index.test.js but there aren't any real tests yet:

```js
import VolumeViewer from "..";

describe("VolumeViewer", () => {
  it("is truthy", () => {
    expect(VolumeViewer).toBeTruthy();
  });
});
```

I suppose we keep it and add in the real tests later?

2021-11-23 13:20 UTC, mcmcgrath13 requested changes

2021-11-23 13:20 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
>        - run: npm publish
```suggestion
      - run: npm ci
      - run: npm test
      - run: npm build
      - run: npm publish
```

Then delete the needs on line 22 and the whole build step.  Splitting this into two jobs doesn't seem beneficial in this case

2021-11-23 13:20 UTC, mcmcgrath13 commented on .github/workflows/npm-publish.yml
>        - run: npm publish
I'm assuming we need a build step and publish doesn't handle that, but I could be wrong - you know the code best

2021-11-23 15:48 UTC, RobertGemmaJr commented
Had to adjust the Jest settings to get the tests to run properly but it should be all set now, everything passes. `package.json` includes a `predeploy` and `deploy` script which builds the example project on gh-pages. It came with the `create-react-library` script, I figure we might as well keep it?

2021-11-23 16:00 UTC, mcmcgrath13 commented on package.json
>      "styled-components": "^5.0.0"
react and react-dom are definitely peer dependencies, but the others strike me as maybe being dependencies - @broarr what do you think?

2021-11-23 16:08 UTC, RobertGemmaJr commented on package.json
>      "styled-components": "^5.0.0"
I know `styled-components` recommends it being a peer dependency but I'm not sure about the other 3

2021-11-23 17:12 UTC, RobertGemmaJr commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
It looks like the github token `${{ secrets.GITHUB_TOKEN }}` is automatically added to the project so I just removed them.

2021-11-30 21:01 UTC, RobertGemmaJr commented on package.json
>      "styled-components": "^5.0.0"
Yeah I think it's best the others stay as dependencies, I'll revert that

2021-11-30 21:13 UTC, RobertGemmaJr commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
I was able to run both `npm run predeploy` and `npm run deploy` from my terminal. I assume it's because I'm already logged in to github there but I don't know if the action will need a separate token

2021-11-30 21:17 UTC, mcmcgrath13 approved these changes
Let's give it a shot! I'm 99% sure the CI won't work as expected on the first try (because it almost never does), so be prepared to debug the first release a bit after this still.

2021-11-30 21:19 UTC, merged